language: go

go:
  - 1.6

matrix:
  - fast_finish: true

install:
  - export GOPATH=$HOME/gopath
  - export PATH=$PATH:$HOME/gopath/bin
  - make clean

script:
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - make build
  - make test
